# Generated by Django 2.1.2 on 2018-10-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticketbooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromplace', models.CharField(max_length=10)),
                ('toplace', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('journeydate', models.DateField()),
                ('searchtrain', models.CharField(max_length=10)),
            ],
        ),
    ]
