# Generated by Django 2.1.2 on 2018-10-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_ticketbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardtype', models.CharField(max_length=5)),
                ('bankname', models.CharField(max_length=5)),
                ('cardholdername', models.CharField(max_length=5)),
                ('cardnumber', models.IntegerField(default=11)),
                ('cvvno', models.IntegerField(default=3)),
            ],
        ),
    ]
