# Generated by Django 2.1.2 on 2018-10-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bankname',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardholdername',
            field=models.CharField(max_length=10),
        ),
    ]
